### ISSUE TITLE
Statistics with custom and predefined queries [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#541]
The current statistics section only features "Case Count by Age and Sex" with a few filters. Supervisors and national users should be able to get additional aggregated data simmilar to what SurvStat does.

@hzi-braunschweig 
Given that we should not build everything that SurvStat can at once: What should be our next steps with this? What fields and aggregated data is important for SORMAS users? What would they use this data for?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 

-[ ] SORMAS statistics section should allows retrieval of aggregated data from a limited version of the SORMAS notification system database. Queries can be created individually or customized from pre-defined queries to generate tables, charts, and maps according to the user's needs
Two major query points
-[ ] **Select query menu or tab**(list of pre-defined queries)
-[ ] **Create query menu or tab** (individual creation of queries- flexible analysis of subsets of entire data sets e.g. disease, status, or epi week/month or year)
  
**Create query menu or tab** 
-[ ] Subsets of SORMAS data set
       -[ ] All diseases within SORMAS
       -[ ] All case classification filter (Suspected, Confirmed, Probable, Not yet classified and Not a case)

**Select query menu or tab** ( all drop down fields must be multiple selectable items within each field)
-[ ] Attributes description of notification category for  Time, Place and Person
-[ ] **Notification Category** (Select epidemic disease, week of notification or month of notification or year of notification)
**Time**
-[ ] Selected disease  by epi week of notification, month or year (52 epi weeks in total) of notification which defines the number of reported disease initial notifications by year of notification
**Place**
-[ ] State/Region/District
**Person**
-[ ]  Sex (male/female)
-[ ]  Age stratified by: 0-4 year intervals, 5-14 year intervals, 15 and above, Unknown
**Display Attributes**
-[ ] In rows for any of the notification, time, person or place data sets
-[ ] In columns for any of the notification, time, person or place data sets
*Display options** (check boxes)
-[ ] Incidence
-[ ] Case counts
-[ ] Zero values
-[ ] Totals
**Data Status reporting period**
-[ ] Select reporting period dates/epi weeks before export (e.g Last published today's date as of 04/04/2018 (until end of week 11, 2018) or Annual/Monthly report 2017 or 2018
**Results**
Display results below selection query with function to download zip file or download individual maps and diagrams

https://survstat.rki.de/Content/Instruction/Content.aspx
https://survstat.rki.de/Content/Query/Create.aspx
https://survstat.rki.de/Content/Query/Main.aspx#SelectQuery

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
This is my basic understanding:

It should be possible to create custom queries for aggregated data similar to what SurvStat@RKI 2.0 does. This means the user should be able to pick filter by attributes based on time, place, person and case data (disease, classification) and select the displayed attributes for rows and columns. A table will show aggregated data (case counts) based on this. 

In addition the user can pick from a set of queries that predefine filters and attributes.

Visualization based on diagrams or a map is not done at this point.

Two questions:

1. With "select query" you are refering to predefined queries like this? https://survstat.rki.de/Content/Query/Select.aspx What predefined queries do we need for the first implemenation round?
2. Notification referes to the point in time where a case is reported?

**Comment by MartinWahnschaffeSymeda** [comment]
Very important from our discussion today:
- maps and diagrams are crucial, we have to find an easy first solution for the map (until the component is replaced with a more powerful one)
- contacts will also be relavant here, but be added later

== Fields for the statistic
=== Time
- week, month, year of onset
- week, month, year of reception
- week, month, year of report

=== Place
- region, district

=== Person
- Sex: male/female
- Age stratified by: 0-4 year intervals, 5-14 year intervals, 15 and above, Unknown

=== Case
- disease
- classification
- outcome

== Display options (check boxes)
- Incidence (instead of case counts)
- Zero values
- Totals

**Comment by MartinWahnschaffeSymeda** [comment]
#569 first

Implementation

- [ ] define enum with all fields
- [ ] provide value options for each field (2017-01, ....)
- [ ] use ExtendedTokenField for the filters: https://vaadin.com/directory/component/extended-token-field/0.3.0
- [ ] time filters (year, etc.): pick date entries, pick between onset, reception, report date
- [ ] from-to filter: pick date range and pick between onset, reception, report date
- [ ] place filter will filter region and district at the same time (see SurvStat)
- [ ] person and case filters: pick entries (similar to time filters)
- [ ] attribute selector. For time filters pick between onset, reception, report date
- [ ] extend case criteria: needs to have fields with a list of the needed values (SQL "IN" query). Unclear if criteria query is able to work with SQL date funtions (e.g. year of date of onset)
- [ ] query returns case counts grouped by display attributes
- [ ] display results in a grid

Display options (incidence, etc.) will be done in another ticket. Same goes for diagrams and the map visualization.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
First prototype is ready. What I've done:
- added new StatisticsView (old is now "basic")
- added ExtendedTokenField dependency
- CaseStatisticsField and StatisticsSubField define possible filter and grouping fields
- StatisticsCaseCriteria for query filter values
- added CaseFacade.queryCaseCount with prototype of native SQL query that can filter by onset year and group by region
Important: time filters have been "turned around". The user should first select onset, reception or report and as second step the time period.

Next steps:

- [ ] add second grouping to query
- [ ] add fields to select grouping
- [ ] replace result label with a grid
- [ ] build a component (or multiple) for the filters
- [ ] extend StatisticsCaseCriteria and the query
- [ ] allow users to add/remove multiple filters

**Comment by MartinWahnschaffeSymeda** [comment]
Notes from the meeting:

- [ ] give access to supervisors and observers as well
- [ ] add short disclaimer on what data is used (so it's clear to supervisors that data of whole country is aggregated)
- [ ] empty result should at least show an info text
- [ ] zero value option is very important and should be active by default
- [ ] incidence: population data has also to be filtered and grouped (age, gender)
- [ ] add basic age groups like in old statistics (<1, <5, <15, 15+)
- predefined queries are not needed now

Bugs/Problems:

- [ ] region/district filter: currently it's not possible to filter only by district
- [ ] on sormas.symeda.de when selecting onset, the full date range starting from 1890 is used - may be related to invalid onset dates in the system, but we have to deal with this.
- [ ] gender: unknown is missing for filters
- [ ] sorting of age groups in table seems to be alphabetic
